Import Library

Untuk nomor 9:
Jika nilai ‘horsepower’ <= 105, tampilkan ‘lower’ + ‘nama origin’ pada baris yang sama. Contohnya ‘lower USA’. 
Jika nilai ‘horsepower’ > 105, tampilkan ‘upper’ + ‘nama origin’.
kalau sudah selesai, bisa kalian upload tugasnya ke GitHub kalian masing-masing, lalu kirim link emailnya ke Brigita.gems@gmail.com dengan subject: latihan data analysis_Nama


In [8]:
import pandas as pd
import numpy as np

a) Buatlah sebuah array dengan perintah arrange yang nilai start dan end adalah sebuah input
b) Dari array yang terbentuk tersebut, buatlah versi 2 dan 3 dimensinya!

In [158]:
start=int(input('Mulai: '))
end=int(input('Selesai: '))

Mulai: 1
Selesai: 13


In [159]:
array_awal= np.arange(start,end)
array_awal

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [160]:
array_awal.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [161]:
array_awal.reshape(2,3,-1)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [190]:
start=int(input('Mulai: '))
end=int(input('Selesai: '))

Mulai: 1
Selesai: 28


In [191]:
array_=np.arange(start,end)
array_

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [192]:
array_.reshape(3,-3)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [193]:
array_.reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [163]:
start=int(input('Mulai: '))
end=int(input('Selesai: '))
n=int(input('Jumlah data: '))

Mulai: 1
Selesai: 21
Jumlah data: 40


In [164]:
data=np.random.randint(start,end,n)
data

array([ 5, 10,  8, 16, 13,  6, 13,  5,  3, 12, 13,  7,  9, 12,  2, 16,  2,
       18,  5,  6, 14,  6,  8,  7, 10,  4,  1, 10, 10, 19, 12,  8,  8, 12,
        8,  1, 18,  9, 20,  9])

In [165]:
matrix=data.reshape(8,-5)
matrix

array([[ 5, 10,  8, 16, 13],
       [ 6, 13,  5,  3, 12],
       [13,  7,  9, 12,  2],
       [16,  2, 18,  5,  6],
       [14,  6,  8,  7, 10],
       [ 4,  1, 10, 10, 19],
       [12,  8,  8, 12,  8],
       [ 1, 18,  9, 20,  9]])

In [166]:
np.fliplr(matrix)

array([[13, 16,  8, 10,  5],
       [12,  3,  5, 13,  6],
       [ 2, 12,  9,  7, 13],
       [ 6,  5, 18,  2, 16],
       [10,  7,  8,  6, 14],
       [19, 10, 10,  1,  4],
       [ 8, 12,  8,  8, 12],
       [ 9, 20,  9, 18,  1]])

In [167]:
matrix[:,::-1]

array([[13, 16,  8, 10,  5],
       [12,  3,  5, 13,  6],
       [ 2, 12,  9,  7, 13],
       [ 6,  5, 18,  2, 16],
       [10,  7,  8,  6, 14],
       [19, 10, 10,  1,  4],
       [ 8, 12,  8,  8, 12],
       [ 9, 20,  9, 18,  1]])

In [194]:
start=int(input('Mulai: '))
end=int(input('Selesai: '))
n=int(input('Jumlah data: '))

Mulai: 1
Selesai: 50
Jumlah data: 16


In [195]:
data1=np.random.randint(start,end,n)
data1

array([44, 39, 43, 29,  1, 32, 16, 34,  6,  7, 29, 47, 42, 37,  5,  9])

In [196]:
matrix1=data1.reshape(4,4)
matrix1

array([[44, 39, 43, 29],
       [ 1, 32, 16, 34],
       [ 6,  7, 29, 47],
       [42, 37,  5,  9]])

In [197]:
np.fliplr(matrix1)

array([[29, 43, 39, 44],
       [34, 16, 32,  1],
       [47, 29,  7,  6],
       [ 9,  5, 37, 42]])

In [37]:
np.random.randint(1,50,16)

array([37, 21, 45,  9,  9, 10, 15, 29, 13, 13, 33, 26, 22, 14, 13, 47])

In [39]:
np.random.randint(1,50,16).reshape(4,4)

array([[47, 41, 24, 38],
       [ 2, 18, 30, 38],
       [23, 45, 20, 49],
       [ 2, 48, 14, 22]])

In [40]:
np.random.randint(1,50,16).reshape(4,-1)

array([[28, 17, 10, 13],
       [39, 46, 21, 25],
       [36, 45, 34, 10],
       [36,  4, 31, 14]])

In [172]:
my_array1=np.ones((10,10))*4
my_array1[1:-1,1:-1]=0
my_array1

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [200]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
myList=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
labels=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
pd.Series(myList,labels)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

In [173]:
import string
labels=list(string.ascii_lowercase)
arr1=np.arange(1,27)
pd.Series(arr1,labels)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int32

In [174]:
my_series= pd.Series(np.random.randint(1,5,100))
my_series

0     4
1     3
2     3
3     3
4     2
     ..
95    4
96    2
97    1
98    2
99    4
Length: 100, dtype: int32

In [175]:
my_series.value_counts()

3    29
2    25
4    23
1    23
dtype: int64

In [181]:
pd.DataFrame(my_series.value_counts().reset_index()).rename(columns={'index':'value',0:'frekuensi'}).head(2)

value  frekuensi
0      3         29
1      2         25

In [178]:
data = np.random.randint(1,5,size=100)
df = pd.DataFrame(data)
print(df)
print(df.dtypes)

    0
0   1
1   3
2   4
3   3
4   4
.. ..
95  2
96  2
97  4
98  4
99  2

[100 rows x 1 columns]
0    int32
dtype: object


In [179]:
counts, unique = np.unique(df, return_counts=True)
pd.Series(counts, unique)

23    1
27    2
24    3
26    4
dtype: int32

In [ ]:
pd.DataFrame(data.value_counts().reset_index()).rename(columns={'index':'value',0:'frekuensi'}).head(2)

In [182]:
import seaborn as sns

In [111]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [112]:
MPG = sns.load_dataset("mpg")

In [74]:
MPG.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [113]:
MPG.describe(include=object)

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [114]:
MPG.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [115]:
MPG.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [116]:
MPG[MPG['horsepower'].isna()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [153]:
MPG[MPG['horsepower'].isna()].index

Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

In [183]:
MPG.groupby('model_year').mean()['horsepower']

model_year
70    147.827586
71    107.037037
72    120.178571
73    130.475000
74     94.230769
75    101.066667
76    101.117647
77    105.071429
78     99.694444
79    101.206897
80     77.481481
81     81.035714
82     81.466667
Name: horsepower, dtype: float64

In [119]:
MPG

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

In [188]:
MPG['horsepower'].apply(lambda x: 'lower' if x<=105 else 'upper')+' '+MPG['origin']

0         upper usa
1         upper usa
2         upper usa
3         upper usa
4         upper usa
           ...     
393       lower usa
394    lower europe
395       lower usa
396       lower usa
397       lower usa
Length: 398, dtype: object

In [189]:
['lower' if i<=105 else 'upper' for i in MPG['horsepower']]+(MPG['origin'])

0         upperusa
1         upperusa
2         upperusa
3         upperusa
4         upperusa
          ...     
393       lowerusa
394    lowereurope
395       lowerusa
396       lowerusa
397       lowerusa
Name: origin, Length: 398, dtype: object

In [184]:
def add_horse(x):
    if x['horsepower']<=105:
        return f'lower{x["origin"]}'
    else:
        return f'upper{x["origin"]}'

In [185]:
MPG[['horsepower','origin']].apply(add_horse, axis=1)

0         upperusa
1         upperusa
2         upperusa
3         upperusa
4         upperusa
          ...     
393       lowerusa
394    lowereurope
395       lowerusa
396       lowerusa
397       lowerusa
Length: 398, dtype: object

In [127]:
conditions = [
    (MPG['horsepower'] <= 105),
    (MPG['horsepower'] > 105)
    ]
values = ['lower', 'upper']
MPG['horse_origin'] = np.select(conditions, values)
MPG

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name horse_origin  
0            70     usa  chevrolet chevelle malibu        upper  
1            70     usa          buick skylark 320        upper  
2            70     usa         plymouth satellite        upper  
3            70     usa              amc rebel sst        upper  
4            70     usa                ford torino        upper  
..          ...     ...                        ...          ...  
393          82     usa            ford mustang gl        lower  
394          82  europe                  vw pickup        lower  
395          82     usa              dodge rampage        lower  
396          82     usa                ford ranger        lower  
397          82     usa                 chevy s-10        lower  

[398 rows x 10 columns]

In [187]:
MPG.groupby('origin')['weight'].agg(['mean', 'std','sum','count','min','max']).reset_index()

origin         mean         std     sum  count   min   max
0  europe  2423.300000  490.043191  169631     70  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3361.931727  794.792506  837121    249  1800  5140

In [155]:
MPG.groupby('origin')['weight'].describe()

count         mean         std     min      25%     50%      75%  \
origin                                                                     
europe   70.0  2423.300000  490.043191  1825.0  2067.25  2240.0  2769.75   
japan    79.0  2221.227848  320.497248  1613.0  1985.00  2155.0  2412.50   
usa     249.0  3361.931727  794.792506  1800.0  2720.00  3365.0  4054.00   

           max  
origin          
europe  3820.0  
japan   2930.0  
usa     5140.0